# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\dev\git\anki-plugins\anki-web-browser\src\config_view.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyAttributeOutsideInit,PyPep8Naming
class Ui_ConfigView(object):
    def setupUi(self, ConfigView):
        ConfigView.setObjectName("ConfigView")
        ConfigView.setWindowModality(QtCore.Qt.ApplicationModal)
        ConfigView.resize(535, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(ConfigView.sizePolicy().hasHeightForWidth())
        ConfigView.setSizePolicy(sizePolicy)
        ConfigView.setMinimumSize(QtCore.QSize(0, 0))
        ConfigView.setMaximumSize(QtCore.QSize(1000, 1000))
        ConfigView.setAutoFillBackground(True)
        ConfigView.setStyleSheet("")
        ConfigView.setSizeGripEnabled(False)
        self.verticalLayWidget = QtWidgets.QWidget(ConfigView)
        self.verticalLayWidget.setGeometry(QtCore.QRect(0, 0, 631, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.verticalLayWidget.sizePolicy().hasHeightForWidth())
        self.verticalLayWidget.setSizePolicy(sizePolicy)
        self.verticalLayWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayWidget.setObjectName("verticalLayWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 541, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 520, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayoutTabProv = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        # self.vLayoutTabProv.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.vLayoutTabProv.setContentsMargins(10, 10, 10, 10)
        self.vLayoutTabProv.setSpacing(7)
        self.vLayoutTabProv.setObjectName("vLayoutTabProv")
        self.lbProviders = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.lbProviders.setFont(font)
        self.lbProviders.setObjectName("lbProviders")
        self.vLayoutTabProv.addWidget(self.lbProviders)
        self.tbProviders = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbProviders.sizePolicy().hasHeightForWidth())
        self.tbProviders.setSizePolicy(sizePolicy)
        self.tbProviders.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText)
        self.tbProviders.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbProviders.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbProviders.setColumnCount(2)
        self.tbProviders.setObjectName("tbProviders")
        self.tbProviders.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbProviders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbProviders.setHorizontalHeaderItem(1, item)
        self.tbProviders.horizontalHeader().setStretchLastSection(True)
        self.tbProviders.verticalHeader().setVisible(False)
        self.vLayoutTabProv.addWidget(self.tbProviders)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(100, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btProviderUp = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btProviderUp.setObjectName("btProviderUp")
        self.horizontalLayout_3.addWidget(self.btProviderUp)
        self.btProviderDown = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btProviderDown.setObjectName("btProviderDown")
        self.horizontalLayout_3.addWidget(self.btProviderDown)
        self.btSortProvider = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btSortProvider.setObjectName("btSortProvider")
        self.horizontalLayout_3.addWidget(self.btSortProvider)
        self.btRemove = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btRemove.setObjectName("btRemove")
        self.horizontalLayout_3.addWidget(self.btRemove)
        self.btAdd = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btAdd.setObjectName("btAdd")
        self.horizontalLayout_3.addWidget(self.btAdd)
        self.vLayoutTabProv.addLayout(self.horizontalLayout_3)
        spacerProvider = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vLayoutTabProv.addSpacerItem(spacerProvider)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbWordFilter = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbWordFilter.setObjectName("lbWordFilter")
        self.horizontalLayout_4.addWidget(self.lbWordFilter)
        self.teWordFilter = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.teWordFilter.setMaximumSize(QtCore.QSize(300, 16777215))
        self.teWordFilter.setObjectName("teWordFilter")
        self.horizontalLayout_4.addWidget(self.teWordFilter)
        self.vLayoutTabProv.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vLayoutTabProv.addWidget(self.line)
        self.lbShortcut = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbShortcut.setFont(font)
        self.lbShortcut.setObjectName("lbShortcut")
        self.vLayoutTabProv.addWidget(self.lbShortcut)
        self.horizontalLayoutShortcuts = QtWidgets.QHBoxLayout()
        self.horizontalLayoutShortcuts.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayoutShortcuts.setObjectName("horizontalLayoutShortcuts")
        self.verticalLayMenu = QtWidgets.QVBoxLayout()
        self.verticalLayMenu.setObjectName("verticalLayMenu")
        self.lbShortMenu = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbShortMenu.setObjectName("lbShortMenu")
        self.verticalLayMenu.addWidget(self.lbShortMenu)
        self.teShortcutMenu = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.teShortcutMenu.setMaximumSize(QtCore.QSize(180, 16777215))
        self.teShortcutMenu.setMaxLength(200)
        self.teShortcutMenu.setObjectName("teShortcutMenu")
        self.verticalLayMenu.addWidget(self.teShortcutMenu)
        self.horizontalLayoutShortcuts.addLayout(self.verticalLayMenu)
        self.verticalLayRepeat = QtWidgets.QVBoxLayout()
        self.verticalLayRepeat.setObjectName("verticalLayRepeat")
        self.lbShortRepeat = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbShortRepeat.setObjectName("lbShortRepeat")
        self.verticalLayRepeat.addWidget(self.lbShortRepeat)
        self.teShortcutRepeat = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.teShortcutRepeat.setMaximumSize(QtCore.QSize(180, 16777215))
        self.teShortcutRepeat.setMaxLength(200)
        self.teShortcutRepeat.setObjectName("teShortcutRepeat")
        self.verticalLayRepeat.addWidget(self.teShortcutRepeat)
        self.horizontalLayoutShortcuts.addLayout(self.verticalLayRepeat)
        self.vLayoutTabProv.addLayout(self.horizontalLayoutShortcuts)
        self.tabWidget.addTab(self.tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 521, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.formLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbSystemBrowser = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.cbSystemBrowser.setObjectName("cbSystemBrowser")
        self.verticalLayout.addWidget(self.cbSystemBrowser)
        self.browserInfo = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browserInfo.sizePolicy().hasHeightForWidth())
        self.browserInfo.setSizePolicy(sizePolicy)
        self.browserInfo.setMinimumSize(QtCore.QSize(0, 30))
        self.browserInfo.setStyleSheet("QLabel  {\n"
"color: rgb(255, 0, 0);\n"
"}")
        self.browserInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.browserInfo.setObjectName("browserInfo")
        self.verticalLayout.addWidget(self.browserInfo)
        self.rbOnTop = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.rbOnTop.setObjectName("rbOnTop")
        self.verticalLayout.addWidget(self.rbOnTop)
        self.rbKeepOpened = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.rbKeepOpened.setObjectName("rbKeepOpened")
        self.verticalLayout.addWidget(self.rbKeepOpened)
        self.cbDarkReader = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.cbDarkReader.setObjectName("cbDarkReader")
        self.verticalLayout.addWidget(self.cbDarkReader)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("text-align: right;\n"
"float: right;")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.leWidth = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leWidth.sizePolicy().hasHeightForWidth())
        self.leWidth.setSizePolicy(sizePolicy)
        self.leWidth.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leWidth.setMaxLength(6)
        self.leWidth.setObjectName("leWidth")
        self.horizontalLayout_5.addWidget(self.leWidth)
        self.leHeight = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leHeight.sizePolicy().hasHeightForWidth())
        self.leHeight.setSizePolicy(sizePolicy)
        self.leHeight.setMinimumSize(QtCore.QSize(100, 0))
        self.leHeight.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leHeight.setMaxLength(6)
        self.leHeight.setObjectName("leHeight")
        self.horizontalLayout_5.addWidget(self.leHeight)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.bottomInfo = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomInfo.sizePolicy().hasHeightForWidth())
        self.bottomInfo.setSizePolicy(sizePolicy)
        self.bottomInfo.setMinimumSize(QtCore.QSize(0, 30))
        self.bottomInfo.setStyleSheet("QLabel  {\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.bottomInfo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.bottomInfo.setObjectName("bottomInfo")
        self.verticalLayout.addWidget(self.bottomInfo)
        self.tabWidget.addTab(self.tab, "")
        self.widget = QtWidgets.QWidget(self.verticalLayWidget)
        self.widget.setGeometry(QtCore.QRect(0, 440, 521, 25))
        self.widget.setObjectName("widget")
        self.btActionsBox = QtWidgets.QHBoxLayout(self.widget)
        self.btActionsBox.setContentsMargins(200, 0, 0, 0)
        self.btActionsBox.setSpacing(7)
        self.btActionsBox.setObjectName("btActionsBox")
        self.btSave = QtWidgets.QPushButton(self.widget)
        self.btSave.setObjectName("btSave")
        self.btActionsBox.addWidget(self.btSave)
        self.btCancel = QtWidgets.QPushButton(self.widget)
        self.btCancel.setObjectName("btCancel")
        self.btActionsBox.addWidget(self.btCancel)

        self.retranslateUi(ConfigView)
        QtCore.QMetaObject.connectSlotsByName(ConfigView)

    def retranslateUi(self, ConfigView):
        _translate = QtCore.QCoreApplication.translate
        ConfigView.setWindowTitle(_translate("ConfigView", "Web Browser Config"))
        self.lbProviders.setText(_translate("ConfigView", "Providers"))
        item = self.tbProviders.horizontalHeaderItem(0)
        item.setText(_translate("ConfigView", "Name"))
        item = self.tbProviders.horizontalHeaderItem(1)
        item.setText(_translate("ConfigView", "URL"))
        self.btProviderUp.setText(_translate("ConfigView", "Up"))
        self.btProviderDown.setText(_translate("ConfigView", "Down"))
        self.btSortProvider.setText(_translate("ConfigView", "Sort"))
        self.btRemove.setText(_translate("ConfigView", "Remove"))
        self.btAdd.setText(_translate("ConfigView", "&Add"))
        self.lbWordFilter.setText(_translate("ConfigView", "Filter following words: "))
        self.lbShortcut.setText(_translate("ConfigView", "Shortcuts"))
        self.lbShortMenu.setText(_translate("ConfigView", "Show Web Browser menu"))
        self.lbShortRepeat.setText(_translate("ConfigView", "Search again, repeating last provider"))
        self.tabWidget.setTabText(0, _translate("ConfigView", "Providers/more"))
        self.cbSystemBrowser.setText(_translate("ConfigView", "Use System Browser (instead of Anki-Web-Browser)"))
        self.browserInfo.setText(_translate("ConfigView", "Importing features won\'t work for external browsers"))
        self.rbOnTop.setText(_translate("ConfigView", "Keep always visible (on top)"))
        self.rbKeepOpened.setText(_translate("ConfigView", "Keep browser opened (after current card is changed)"))
        self.cbDarkReader.setText(_translate("ConfigView", "Enable DarkReader (experimental)"))
        self.label.setText(_translate("ConfigView", "Initial size:"))
        self.leWidth.setPlaceholderText(_translate("ConfigView", "Width"))
        self.leHeight.setPlaceholderText(_translate("ConfigView", "Height"))
        self.bottomInfo.setText(_translate("ConfigView", "It may be necessary to restart Anki to apply the changes"))
        self.tabWidget.setTabText(1, _translate("ConfigView", "Behaviour"))
        self.btSave.setText(_translate("ConfigView", "&Save"))
        self.btCancel.setText(_translate("ConfigView", "&Cancel"))


